version: '3.8'

services:
  postgres_api:
    container_name: ${DB_CONTAINER_NAME}
    image: ${DB_IMAGE}
    restart: on-failure
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT_EXT}:5432"
    volumes:
      - postgres_api_vol:/var/lib/postgresql/data
  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: ${REDIS_IMAGE}
    restart: on-failure
    ports:
      - "${REDIS_PORT_EXT}:${REDIS_PORT_INT}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
  redis-insight:
    container_name: ${REDIS_INSIGHT_CONTAINER_NAME}
    image: ${REDIS_INSIGHT_IMAGE}
    restart: on-failure
    ports:
      - "${REDIS_INSIGHT_PORT_EXT}:${REDIS_INSIGHT_PORT_INT}"
    volumes:
      - redis_vol:/data
  postgres_keycloak:
    container_name: ${KEYCLOAK_POSTGRES_CONTAINER_NAME}
    image: ${KEYCLOAK_POSTGRES_IMAGE}
    restart: on-failure
    volumes:
      - postgres_keycloak_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    networks:
      - brazona_net
  keycloak:
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    image: ${KEYCLOAK_IMAGE}
    command: ${KEYCLOAK_COMMAND}
    restart: on-failure
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${KEYCLOAK_POSTGRES_CONTAINER_NAME}/${KEYCLOAK_POSTGRES_DB}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    ports:
      - "${KEYCLOAK_PORT_EXT}:8080"
    depends_on:
      - postgres_keycloak
    networks:
      - brazona_net
volumes:
  postgres_keycloak_vol:
    driver: local
  postgres_api_vol:
    driver: local
  redis_vol:
    driver: local
networks:
  brazona_net:
    driver: bridge