server:
  port: ${APP_API_PORT}
  servlet:
    context-path: /api
spring:
  application:
    name: idp-api
  main:
    web-application-type: servlet
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          issuer-uri: http://localhost:8081/realms/brazona
  datasource:
    url: jdbc:postgresql://${APP_API_DB_HOST}:${APP_API_DB_PORT_EXT}/${APP_API_DB_NAME}
    password: ${APP_API_DB_PASS}
    user: ${APP_API_DB_USER}
    hikari:
      connection-timeout: '20000'
      idle-timeout: '10000'
      maximum-pool-size: '40'
      auto-commit: 'true'
      minimum-idle: '10'
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: jdbc:postgresql://${APP_API_DB_HOST}:${APP_API_DB_PORT_EXT}/${APP_API_DB_NAME}
    password: ${APP_API_DB_PASS}
    user: ${APP_API_DB_USER}
    enabled: false
    change-log: classpath:db/changelog-master.yml
    parameters:
      sql_user_name_1: ${APP_API_DB_SQL_USER_NAME_1}
      sql_user_name_2: ${APP_API_DB_SQL_USER_NAME_2}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
ribbon:
  ReadTimeout: '20000'
  ConnectTimeout: '10000'
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: '60000'
authorization:
  jwt:
    secret: ${APP_API_AUTHORIZATION_JWT_SECRET}
oauth:
  client:
    secret: ${APP_API_AUTHENTICATION_PASS}
    name: ${APP_API_AUTHENTICATION_USER}
logging:
  level:
    liquibase: debug
    org:
      springframework:
        security: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  swagger-ui:
    csrf:
      enabled: true
  api-docs:
    path: /api-docs
jwt:
  auth:
    converter:
      resource-id: idp
      principal-attribute: principal_username
keycloak:
  url: ${KEYCLOAK_URL}
  name: ${KEYCLOAK_NAME}
  grant: ${KEYCLOAK_GRANT_TYPE}
  client: ${KEYCLOAK_CLIENT_ID}

teste: ${KEYCLOAK_URL}