version: '3.0'

services:
  api:
    container_name: ${CONTAINER_NAME_API}
    hostname: ${CONTAINER_NAME_API}
    build:
      context: ./api
    networks:
      - bza-network
    extra_hosts:
    - "host.docker.internal:host-gateway"  
    restart: always  
    environment:
    - SPRING_ACTIVE_PROFILE=${SPRING_ACTIVE_PROFILE}
    - CONFIG_SERVER_HOST=${CONFIG_SERVER_HOST}
    - CONFIG_SERVER_USER=${CONFIG_SERVER_USER}
    - CONFIG_SERVER_PASS=${CONFIG_SERVER_PASS}
    - DB_SERVER_HOST=${DB_SERVER_HOST}
    ports:
      - "${API_PORT_EXTERNAL}:${API_PORT_INTERNAL}"
  ui:
    container_name: ${CONTAINER_NAME_UI}
    hostname: ${CONTAINER_NAME_UI}
    build:
      context: ./ui
    networks:
      - bza-network
    restart: always
    depends_on:
      - api  
    environment:
    - APP_API_URL=${APP_API_URL}
    - APP_API_HOST=${APP_API_HOST}
    - APP_API_PORT=${APP_API_PORT}
    - APP_API_BASIC_USER=${APP_API_BASIC_USER}
    - APP_API_BASIC_PASS=${APP_API_BASIC_PASS}
    
    ports:
      - "${UI_PORT_EXTERNAL}:${UI_PORT_INTERNAL}"
networks:
  bza-network:
    external: true