---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp-ui
  namespace: ${NAMESPACE}
  labels:
    app: idp-ui
spec:
  selector:
    matchLabels:
      app: idp-ui
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: idp-ui
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
      - name: idp-ui-service
        image: ${IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 7782
          protocol: TCP
        env:
          - name: SPRING_ACTIVE_PROFILE
            valueFrom:
              configMapKeyRef:
                name: idp-ui-service           
                key: SPRING_ACTIVE_PROFILE
          
          - name: GITHUB_TOKEN
            valueFrom:
              configMapKeyRef:
                name: idp-ui-service           
                key: GITHUB_TOKEN  

          - name: GITHUB_USER
            valueFrom:
              configMapKeyRef:
                name: idp-ui-service           
                key: GITHUB_USER   

          - name: CONFIG_SERVER_PASS
            valueFrom:
              configMapKeyRef:
                name: idp-ui-service           
                key: CONFIG_SERVER_PASS

          - name: CONFIG_SERVER_ENCRYPT_KEY
            valueFrom:
              configMapKeyRef:
                name: idp-ui-service           
                key: CONFIG_SERVER_ENCRYPT_KEY

          - name: GITHUB_BRANCH
            valueFrom:
              configMapKeyRef:
                name: idp-ui-service           
                key: GITHUB_BRANCH

          - name: GITHUB_URL
            valueFrom:
              configMapKeyRef:
                name: idp-ui-service           
                key: GITHUB_URL     

---
kind: Service
apiVersion: v1
metadata:
  name: idp-ui-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: idp-ui
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 7782
      targetPort: 7782

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: idp-ui-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: ${DNS}
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: idp-ui-service
              port:
                number: 7782